version: '3'

services:
  server:
    image: jitaodocker/hgfr_eval_server
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      default:
        ipv4_address: 10.0.0.1

networks:
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.0.0/16