version: '3'

services:
  client:
    image: jitaodocker/hgfr_eval_client
    deploy:
      replicas: 40
    # volumes:
    #   - /hgfreval/test/log:/tmp/log
    environment:
      - bootstrap_ip=${EVAL_SERVER_IP}

networks:
  default:
    external:
      name: hgfr_default