version: '3'

services:
  server:
    image: jitaodocker/hgfr_eval_server
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: "no"
    stdin_open: true
    tty: true
    networks:
      - default

networks:
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.0.0/16